### ISSUE TITLE
Filenotfounderror: WML Credentials not found

### ISSUE THREAD

**Issue by Aruna-Saraswathy** [IBM/mlflow-watsonml#18]
I installed the plugin and when I tried to call it, I am getting this error, im trying this in IBM cloud 
<img width="1362" alt="Screenshot 2023-02-28 at 7 35 37 PM" src="https://user-images.githubusercontent.com/38246335/221877576-cf8889d9-3f21-4ae4-b7c8-a14b92922c5a.png">

**Comment by DhavalRepo18** [comment]
@dhruv5995 Do you think the new release has addressed this issue?

**Comment by dhruv5995** [comment]
Hi @Aruna-Saraswathy you need to provide the WML credentials and a deployment space name in order to be able to connect to the WML API Client. Please refer to the following [file](https://github.com/IBM/mlflow-watsonml/blob/fdbbe870f2536cbebf6e21f2b477276f75d6e769/.env.template) and based on the case that applies to you, create a `.env` file in the same directory as `.env.template`. This will enable the authentication and connection to the WML API Client.

**Comment by dhruv5995** [comment]
Closing this now. Feel free to reopen if you have any questions or problem using the plugin.
